
-- Generated by ORDS REST Data Services 26.1.0.r0791128
-- Schema: PRINCIPAL  Date: Thu Apr 30 06:06:19 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'principal',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'set_comprobante',
      p_base_path      => '/set_comprobante/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'set_comprobante',
      p_pattern        => 'cargar',
      p_priority       => 5,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'set_comprobante',
      p_pattern        => 'cargar',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => 'application/json',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    pkg_set_comprobante.recibir_json(:body);
END;');

  ORDS.CREATE_ROLE(
      p_role_name=> 'rol.kmelot');
  l_roles(1) := 'rol.kmelot';
  l_modules(1) := 'set_comprobante';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'privilegio.kmelot',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'privilegio.kmelot',
      p_description    => NULL,
      p_comments       => NULL); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;